// <auto-generated />
using Crypto.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Crypto.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180414131244_Again1")]
    partial class Again1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Crypto.Models.Report", b =>
                {
                    b.Property<int>("ReportID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AcountReported");

                    b.Property<int>("AcountReporting");

                    b.Property<bool>("Active");

                    b.Property<string>("Description");

                    b.Property<string>("Reason");

                    b.HasKey("ReportID");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("Crypto.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AcountId");

                    b.Property<bool>("Active");

                    b.Property<int>("Amount");

                    b.Property<int>("AmountWanted");

                    b.Property<string>("CurrencyType");

                    b.Property<string>("CurrrencyWanted");

                    b.Property<string>("TransactionDescription");

                    b.Property<string>("TransactionInfo");

                    b.Property<string>("TransactionTitle");

                    b.Property<string>("UserName");

                    b.Property<string>("Wallet");

                    b.HasKey("TransactionId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Crypto.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AcountID");

                    b.Property<string>("Password");

                    b.Property<string>("PicUrl");

                    b.Property<string>("UserName");

                    b.Property<string>("Wallet");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Crypto.Models.Wallet", b =>
                {
                    b.Property<int>("WalletID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CurrencyType");

                    b.Property<int>("UserID");

                    b.Property<string>("WalletName");

                    b.HasKey("WalletID");

                    b.ToTable("Wallets");
                });
#pragma warning restore 612, 618
        }
    }
}
